### ISSUE TITLE
date parse failure

### ISSUE THREAD

**Issue by adamdecaf** [shift/domain_exporter#11]
I was trying out `quay.io/shift/domain_exporter:v0.1.6` and ran into a domain whose date didn't parse. The parsing works fine on master.

I also noticed the `docker/domain_exporter` is old (Feb 14th) and doesn't even have `/probe`. 

The metric I get is: 

```
# HELP domain_expiration Days until the WHOIS record states this domain will expire
# TYPE domain_expiration gauge
domain_expiration{domain="..."} -1
```

**Comment by shift** [comment]
`docker/domain_exporter` is now deprecated it was a hack to build the original docker container. I've got a WIP branch which removes this along with some other changes. What (c)TLD did the parse error happen on out of interest? I'm busy working out a test suite for the exporter at the moment and would add it as a regression test.

**Comment by adamdecaf** [comment]
It was a `com` TLD. Here's part of the whois response.

```
Registrar WHOIS Server: whois.publicdomainregistry.com
Registrar URL: www.publicdomainregistry.com
Updated Date: 2017-06-28T19:53:15Z
Creation Date: 2007-07-03T19:06:09Z
Registrar Registration Expiration Date: 2018-07-03T19:06:09Z
Registrar: PDR Ltd. d/b/a PublicDomainRegistry.com
Registrar IANA ID: 303
Domain Status: OK https://icann.org/epp#OK
Registry Registrant ID: Not Available From Registry
```

**Comment by adamdecaf** [comment]
Here's another pattern (for `io` domains).

```
Registry Expiry Date: 2018-12-21T17:35:22Z
```

I can bring back [adamdecaf/go-whois](https://github.com/adamdecaf/go-whois), but I thought there was a better Go whois parser already available.
