### ISSUE TITLE
When a domain response is unparseable, there is nothing in the prometheus scrape to indicate it

### ISSUE THREAD

**Issue by Vaelatern** [shift/domain_exporter#21]
To be specific, the `parse` function returns `-1, err` instead of `days, nil`, and this means, ultimately, the monitoring Prometheus instance won't necessarily tell me that the domain is missing.

Perhaps a separate metric should be exported for "Was unable to parse"?

Would a patch implementing this be considered?

**Comment by shift** [comment]
A patch for this would be welcome yeah.
