### ISSUE TITLE
New docker build

### ISSUE THREAD

**Issue by razius** [shift/domain_exporter#27]
Can you please build and push the new image?

Thank you.

**Comment by adamdecaf** [comment]
Yep! I pushed `v0.1.8` and am waiting for the docker build/push.

https://github.com/shift/domain_exporter/releases/tag/v0.1.8

**Comment by adamdecaf** [comment]
@razius You should be able to pull an image now. 

@shift Do we want to manually tag `v0.1.8` from the Go 1.11 image?

```
$ docker pull quay.io/shift/domain_exporter:v0.1.8-go1.11.4
v0.1.8-go1.11.4: Pulling from shift/domain_exporter
30fe3e668b26: Pull complete 
Digest: sha256:0494b51edc9f4e81e567115da25328491a77abce42e6647504034bf25b7b3c24
Status: Downloaded newer image for quay.io/shift/domain_exporter:v0.1.8-go1.11.4
```
