### ISSUE TITLE
Manual expiration date specification

### ISSUE THREAD

**Issue by razius** [shift/domain_exporter#28]
A lot of European TLD's don't expose the expiration date when running whois so data is not available in Prometheus.

Right now I'm managing these via a calendar entry but and I'm thinking that it would be very useful to have a static expiration date specified in the config. This way the same alerts can be used for both cases.

Would there be any interest in me adding this to the code-base?

See following: https://serverfault.com/questions/766424/domain-renewal-expiration-date-for-european-domains-whois

**Comment by adamdecaf** [comment]
TIL. Could the expiration be scraped with [RDAP](https://www.icann.org/rdap)? It's an _eventual_ replacement for WHOIS. 

I maintain an exporter and would help get those TLD's supported in it. 

https://github.com/adamdecaf/rdap_exporter

**Comment by razius** [comment]
Not familiar with RDAP, how will this work?

**Comment by adamdecaf** [comment]
It's an alternate to WHOIS, but I don't think those TLD's are supported.

```
$ rdap forelli.eu
# Error: No RDAP servers found for 'forelli.eu'
```

Nevermind - that was off track.

**Comment by adamdecaf** [comment]
What would the configuration format look like? 

```yaml
static_expirations:
 - "foo.com": <iso-datetime>
```

**Comment by razius** [comment]
Yes, that's what I was thinking.

**Comment by adamdecaf** [comment]
Sounds good to me! Do you want to create a Pull Request?

**Comment by razius** [comment]
Yes, I'll work through it and send a pull request. Will take me a bit as I've never written in go up until now.

**Comment by adamdecaf** [comment]
Did you want some help getting the change worked on? You could push up what code you've got so far.

**Comment by SuperQ** [comment]
This doesn't make any sense to me. If there's no data to gather, there's really no point in creating fake monitoring here.

**Comment by shift** [comment]
Closing as its dangling with no updates. I agree with @SuperQ though, If you need to know when to renew a domain on a set schedule, use a calendar reminder or something else, don't abuse this exporter for it, its not the place.
