### ISSUE TITLE
domains with multiple dots are not working

### ISSUE THREAD

**Issue by Ravikanthreddy** [shift/domain_exporter#33]
i have some domains like www.google.com that gives me correct expiration dates.

If there are some domains like www.api.google.com then it doesnt work. Same goes with other domains as well where multiple dots are present. Most of them resolve to main domain with single dot though. But worst case in case some domains are pointed to different domains and have different expiration dates, then its not working.

Can this be included in it please? in short www.google.com works, and api.google.com or m.google.com doesnt work. Not specifically google domains though :)

**Comment by adamdecaf** [comment]
What does it even mean for a subdomain to have WHOIS information? The root domain (`google.com`) is what matters.

**Comment by Ravikanthreddy** [comment]
Completely agree. But came across situation where some subdomains are pointing to different root domains as a configuration issue, and would like to track them. In short, WHOIS information is retrieved for xyz.com and m.xyz.com (although both are same.). But domain exporter works or gives expiry dates validity only for xyz.com and doesnt retrieve or gives -1 for m.xyz.com. Data is and should be same for both, but i would like to track them both.

**Comment by adamdecaf** [comment]
It looks like we'd need to do domain specific changes here, which I'm not in favor of. `m.google.com` and `www.api.google.com` give a "NOT FOUND" from whois.

```
No match for domain "WWW.API.GOOGLE.COM".
>>> Last update of whois database: 2019-10-15T16:02:57Z <<<
```

```
$ cat testdata/domains.yaml 
domains:
  - www.api.google.com
  - google.com

$ go run main.go --config testdata/domains.yaml 
level=info ts=2019-10-15T15:57:10.691Z caller=main.go:81 msg="Starting domain_exporter" version="(version=, branch=, revision=)"
level=info ts=2019-10-15T15:57:10.691Z caller=main.go:82 msg="Build context" (gogo1.13.1,user,date)=(MISSING)
level=info ts=2019-10-15T15:57:10.692Z caller=main.go:122 msg=Listening port=:9203
level=warn ts=2019-10-15T15:57:11.007Z caller=main.go:169 warn="Don't know how to parse domain: www.api.google.com"
level=warn ts=2019-10-15T15:57:11.007Z caller=main.go:109 warn="Don't know how to parse domain: www.api.google.com"
level=info ts=2019-10-15T15:57:11.119Z caller=main.go:176 domain:=google.com days=3256 date=2028-09-14T04:00:00Z

$ curl -s localhost:9203/metrics | grep google
domain_expiration{domain="google.com"} 3256
domain_expiration_unfindable{domain="google.com"} 0
domain_expiration_unfindable{domain="www.api.google.com"} 1
```

**Comment by Ravikanthreddy** [comment]
Sorry for the bad example. May be you can consider this.
www.facebook.com - gives 3255 days
m.facebook.com - gives  -1.
Expected for m.facebook.com should be 3255 as well.

**Comment by adamdecaf** [comment]
I see the same WHOIS response of "NOT FOUND" for `m.facebook.com` so dates returned seem to be related to their registrar and not the domain.

```
No match for domain "M.FACEBOOK.COM".
>>> Last update of whois database: 2019-10-16T18:04:45Z <<<
```

**Comment by Ravikanthreddy** [comment]
https://www.whois.com/whois/facebook.com

This returns same data for www.facebook.com and m.facebook.com with expiry date details.

however exporter returns correct expiry days for www.facebook.com but for m.facebook.com it returns -1.

**Comment by the-maldridge** [comment]
To add a datapoint to this, it does matter to check subdomains in the case of many country specific TLDs, such as .co.au and .co.il.

**Comment by shift** [comment]
@the-maldridge, correct which is what it does. And in that scenario, its not a subdomain but a fully qualified ccTLD domain. Whois servers only track registered domains, subdomains only exist if the domain is registered and delegated to DNS servers. This use case isn't covered by the domain_exporter, if you want to check subdomains use one of the other exporters, eg. blackbox for checking TLS certificates or DNS records with the domain_exporter checking your domain name hasn't expired.
