### ISSUE TITLE
Support for querying additional country codes

### ISSUE THREAD

**Issue by the-maldridge** [shift/domain_exporter#35]
As #33 was closed without resolution to the original issue (querying valid whois records for domains with more than one dot in them) I'm opening this issue to determine if the solution is to fork this exporter.

There are 255 country code domains which operate in this fashion.  If the best way to add support for these domains which return valid WHOIS records is to fork this code, then please state as such and I will do so.

**Comment by the-maldridge** [comment]
Closing as the registry I wanted to query provides metrics in a more accessible format via another channel.

**Comment by shift** [comment]
This is a subset of the support ccTLDs.
https://github.com/shift/domain_exporter/blob/master/testdata/whois_servers_list
