### ISSUE TITLE
data missing

### ISSUE THREAD

**Issue by imran-baig-se** [shift/domain_exporter#38]
Hello team, i have deployed this on Kubernetes and find data still missing.

![image](https://user-images.githubusercontent.com/25133298/80364232-99800f80-8896-11ea-9148-99673ed3ad58.png)

**Comment by imran-baig-se** [comment]
@adamdecaf 

 k logs domain-exporter-865f89df7c-h7rgs -n monitoring
level=info ts=2020-04-27T10:54:18.251310273Z caller=main.go:81 msg="Starting domain_exporter" version="(version=, branch=, revision=)"
level=info ts=2020-04-27T10:54:18.251355962Z caller=main.go:82 msg="Build context" (godevel+5ec5c5741eWedJan219:31:052019+0000,user,date)=(MISSING)
level=info ts=2020-04-27T10:54:18.251481711Z caller=main.go:122 msg=Listening port=:9203

**Comment by adamdecaf** [comment]
Are your domain metrics missing? What's the config file look like?

**Comment by imran-baig-se** [comment]
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-exporter-config
  labels:
    app: domain-exporter
data:
  domains.yaml: |-
    domains:
      - tajawal.com
      - ae.almosafer.com

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: domain-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domain-exporter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: domain-exporter
    spec:
      containers:
      - name: domain-exporter
        image: quay.io/shift/domain_exporter
        ports:
          - containerPort: 9203
        args: [
          "--config=/etc/domain-exporter/domains.yaml",
          "--bind=:9203",
          "--log.level=info",
        ]
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /etc/domain-exporter
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: domain-exporter-config

---

apiVersion: v1
kind: Service
metadata:
  name: domain-exporter
  annotations:
    prometheus.io/port: "9203"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - port: 9203
    targetPort: 9203
    protocol: TCP
    name: domain-exporter
  selector:
    app: domain-exporter

**Comment by adamdecaf** [comment]
Subdomains haven't worked well to parse expiry from. The only expiry that matters is the root domain, so `almosafer.com`.  https://github.com/shift/domain_exporter/issues/33 talks a bit about this. 

Running that config returns an error as expected.
```
level=info ts=2020-04-29T18:03:31.589Z caller=main.go:175 domain:=tajawal.com date=2020-06-10T06:24:49Z
level=warn ts=2020-04-29T18:03:31.633Z caller=main.go:169 warn="Don't know how to parse domain: ae.almosafer.com"
```

However, checking the root domain works. 
```
level=info ts=2020-04-29T18:03:49.815Z caller=main.go:175 domain:=tajawal.com date=2020-06-10T06:24:49Z
level=info ts=2020-04-29T18:03:49.859Z caller=main.go:175 domain:=almosafer.com date=2026-01-18T14:15:41Z
```

**Comment by imran-baig-se** [comment]
Thanks, @adamdecaf, where do u get this logs I change to root domain and restated

logs 

$ k logs domain-exporter-865f89df7c-7gmbg -n monitoring
level=info ts=2020-05-02T11:11:19.256811023Z caller=main.go:81 msg="Starting domain_exporter" version="(version=, branch=, revision=)"
level=info ts=2020-05-02T11:11:19.256850897Z caller=main.go:82 msg="Build context" (godevel+5ec5c5741eWedJan219:31:052019+0000,user,date)=(MISSING)
level=info ts=2020-05-02T11:11:19.256988846Z caller=main.go:122 msg=Listening port=:9203
level=warn ts=2020-05-02T11:11:49.257158415Z caller=main.go:109 warn="dial tcp 192.30.45.30:43: i/o timeout"
level=warn ts=2020-05-02T11:12:19.257350051Z caller=main.go:109 warn="dial tcp 192.30.45.30:43: i/o timeout"

**Comment by adamdecaf** [comment]
`domain_exporter` can't reach the WHOIS server (see `dial tcp 192.30.45.30:43: i/o timeout`).

Is your Kubernetes cluster or firewall blocking that port? Or perhaps the WHOIS server was down during that test.
