### ISSUE TITLE
/probe endpoint?

### ISSUE THREAD

**Issue by adamdecaf** [shift/domain_exporter#4]
`blackbox_exporter` has a [/probe](https://github.com/prometheus/blackbox_exporter#local-build) endpoint which Prometheus can scrape metrics from. It's a bit non-intuitive, but pretty nice use.

What about a similar endpoint here? I can offer a PR doing so. 

https://github.com/coreos/prometheus-operator/issues/256#issuecomment-359903835

**Comment by shift** [comment]
I think the probe idea is great. I don't have a use case for it myself at the moment so PR's are welcome.

**Comment by shift** [comment]
This has been added on a feature branch currently.

**Comment by shift** [comment]
This is now merged to master and tagged Docker images will be available from quay.io soon. Please check the tags on Quay to find the version you wish you use.

**Comment by adamdecaf** [comment]
Awesome, thanks!
