### ISSUE TITLE
Issues with zone .ch

### ISSUE THREAD

**Issue by Denis-Kvashnin** [shift/domain_exporter#67]
Hello.
We have troubles dealing with your exporter checking .ch zone. Could there be a case that the exporter cannot parse because of this certain zone? I'm getting "Domain unparsable or expire".

**Comment by shift** [comment]
Yeah. There has been a few occasions where by WHOIS servers have changed the formatting used. And others where they've stopped exposing the data and instead refer you to some NIC WHOIS website. I'll take a look at this hopefully later today (CEST).

**Comment by shift** [comment]
So I checked https://www.nic.ch/whois/rdap/ and they use the RDAP protocol rather than the WHOIS protocol. There is actually a fork of this project by one of the maintainers here https://github.com/adamdecaf/rdap_exporter which should meet your requirements.

**Comment by Denis-Kvashnin** [comment]
Great, thanks a lot for solution!

**Comment by shift** [comment]
Not a problem, will close this :)
