### ISSUE TITLE
systemd domain_exporter

### ISSUE THREAD

**Issue by SD3vEng** [shift/domain_exporter#89]
Hi! Tell me how to run domain_exporter in the background and add it to systemd??

**Comment by shift** [comment]
A basic example would be:

```
[Unit]
Description=Domain Exporter

[Service]
User=nobody
ExecStart=/path/to/domain_exporter --config /path/to/config.yaml

[Install]
WantedBy=multi-user.target
```

**Comment by SD3vEng** [comment]
I tried installing the package via yum and rpm, but I couldn't find the installation location and the location of the configuration file
